Pandas

Pandas

Pandas

In [2]:
import pandas as pd

In [3]:
 import pandas as pd
 import numpy as np
 import matplotlib.pyplot as plt
 import glob
 import re
 import math

In [4]:
# For apply Theme
    # ! pip install --upgrade jupyterthemes
    #jt -t oceans16
 # For reset theme
    # !jt -r
 # Create series from numpy array
v = np.array([1,2,3,4,5,6,7])
s1 = pd.Series(v)
s1

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

In [5]:
#Datatype of Series
s1.dtype

dtype('int64')

In [6]:
import pandas as pd
import numpy as np

# Create series from numpy array
v = np.array([1, 2, 3, 4, 5, 6, 7])
s1 = pd.Series(v)

# Get the memory usage of the series
memory_usage = s1.memory_usage(deep=True)
print(f"Memory usage of the series: {memory_usage} bytes")

# Get the number of bytes allocated to each item
itemsize = s1.memory_usage(deep=True) / len(s1)
print(f"Number of bytes allocated to each item: {itemsize} bytes")

Memory usage of the series: 188 bytes
Number of bytes allocated to each item: 26.857142857142858 bytes


In [7]:
 # number of bytes consumed by series
s1.nbytes

56

In [8]:
 # shape of series
s1.shape

(7,)

In [9]:
 # number of dimensions
s1.ndim

1

In [10]:
# Length of Series
len(s1)

7

In [11]:
# Length of Series
s1.count()

np.int64(7)

In [12]:
s1.size

7

In [13]:
 # Create Series from list
s0 = pd.Series([1, 2, 3, 4, 5, 6, 7], index=['a', 'b', 'c', 'd', 'e', 'f', 'g'])
s0

a    1
b    2
c    3
d    4
e    5
f    6
g    7
dtype: int64

In [14]:
 # Modifying index in Series

s2 = pd.Series([1, 2, 3, 4, 5, 6])

X = pd.Series(['a', 'b', 'c', 'd', 'e', 'f'])
s2.index = X
s2

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

In [15]:
 # Creating series using Random and Range function
v2 = np.random.random(10)
ind2 = np.arange(0, 10)
s = pd.Series(v2, ind2)
v2

array([0.35778124, 0.50580158, 0.20164364, 0.08899699, 0.09942859,
       0.13132436, 0.68415641, 0.1506159 , 0.22169402, 0.16764955])

In [16]:
ind2, v2

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0.35778124, 0.50580158, 0.20164364, 0.08899699, 0.09942859,
        0.13132436, 0.68415641, 0.1506159 , 0.22169402, 0.16764955]))

In [17]:
dict = {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}
s3 = pd.Series(dict)
s3

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [18]:
pd.Series(99, index=[0, 1, 2, 3, 4, 5])

0    99
1    99
2    99
3    99
4    99
5    99
dtype: int64

1  Different Things on Series with Pandas

1  Different Things on Series with Pandas

1  Different Things on Series with Pandas

In [19]:
s

0    0.357781
1    0.505802
2    0.201644
3    0.088997
4    0.099429
5    0.131324
6    0.684156
7    0.150616
8    0.221694
9    0.167650
dtype: float64

In [20]:
# Return all elements of the series
s[:]

0    0.357781
1    0.505802
2    0.201644
3    0.088997
4    0.099429
5    0.131324
6    0.684156
7    0.150616
8    0.221694
9    0.167650
dtype: float64

In [21]:
 # First three element of the Series
s[0:3]

0    0.357781
1    0.505802
2    0.201644
dtype: float64

In [22]:
 # Last element of the Series
s[-1:]

9    0.16765
dtype: float64

In [23]:
 # Fetch first 4 elements in a series
s[:4]

0    0.357781
1    0.505802
2    0.201644
3    0.088997
dtype: float64

In [24]:
 # Return all elements of the series except last two elements.
s[:-2]

0    0.357781
1    0.505802
2    0.201644
3    0.088997
4    0.099429
5    0.131324
6    0.684156
7    0.150616
dtype: float64

In [25]:
# Return all elements of the series except last element.
s[:-1]

0    0.357781
1    0.505802
2    0.201644
3    0.088997
4    0.099429
5    0.131324
6    0.684156
7    0.150616
8    0.221694
dtype: float64

In [26]:
 # Return last element of the series
s[-1:]

9    0.16765
dtype: float64

In [27]:
 # Return last two elements of the series
s[-2:]

8    0.221694
9    0.167650
dtype: float64

In [28]:
s[-3:-1]

7    0.150616
8    0.221694
dtype: float64

 1.2  Append Series

 1.2  Append Series

 1.2  Append Series

In [29]:
s2 = s1.copy()
s2

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

In [30]:
s3

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [34]:
# appent s2 & s3 Series
s4 = pd.concat([s2, s3])
s4

0    1
1    2
2    3
3    4
4    5
5    6
6    7
a    1
b    2
c    3
d    4
e    5
dtype: int64

In [37]:
# Drop 'a4' from s4, ignoring errors if the label doesn't exist
s4 = s4.drop('a4', inplace=False, errors='ignore')
print(s4)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
a    1
b    2
c    3
d    4
e    5
dtype: int64


In [38]:
s4

0    1
1    2
2    3
3    4
4    5
5    6
6    7
a    1
b    2
c    3
d    4
e    5
dtype: int64